sudo: required

services:
  - docker

before_install:
  - docker build -t jokirkpa/docker-react -f Dockerfile.dev .

script:
 - docker run -e CI=true jokirkpa/docker-react npm run test

# This will tell Travis CI how to take an application and deploy it to aws
# With "provider" specify elasticbeanstalk as the provider
# With "region" we specify the region, that the elastic beanstalk app was created in
# With "app" we specify the name of the app
# With "env" we specify the environment name
# With "bucket_name" we provide a name of the bucket, that travis CI places a ZIP into
# buckets are generated in the S3 service
# The "bucket_path" is the "app" name as well
# when the specify anytime we push, we push to branch master "on"
# Lastly we add the access and secret key, we saved in Travis CI
 deploy: 
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-01"
  env: "Docker-react-01-env"
  bucket_name: "elasticbeanstalk-us-east-2-295854318539"
  bucket_path: "docker-react-01"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"